#!/bin/env bats
################################################################################
# このファイルは po2bats.sh によって自動生成されました。編集しないでください！
################################################################################
setup() {
  export TEXTDOMAINDIR='/usr/local/share/locale'
  basecmd="gettext -e --domain="po2bats""
}
@test "" {
  run $basecmd ""
  [ "$output" = "$(echo -e "Project-Id-Version: po2bats 0.1.0\nReport-Msgid-Bugs-To: kim <kimkim19642004@yahoo.co.jp>\nPOT-Creation-Date: 2018-07-10 20:46+0900\nPO-Revision-Date: 2018-07-10 20:48+0900\nLast-Translator: kim <kimkim19642004@yahoo.co.jp>\nLanguage-Team: kim <kimkim19642004@yahoo.co.jp>\nLanguage: ja\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nPlural-Forms: nplurals=1; plural=0;\n")" ]
}
@test "Usage" {
  run $basecmd "Usage"
  [ "$output" = "$(echo -e "使用法")" ]
}
@test "OPTION" {
  run $basecmd "OPTION"
  [ "$output" = "$(echo -e "オプション")" ]
}
@test "Generate BATS file from PO file" {
  run $basecmd "Generate BATS file from PO file"
  [ "$output" = "$(echo -e "PO ファイルから BATS ファイルを生成します")" ]
}
@test "Specify message catalog search path" {
  run $basecmd "Specify message catalog search path"
  [ "$output" = "$(echo -e "メッセージカタログの検索パスを指定します")" ]
}
@test "Display message catalog information and exit" {
  run $basecmd "Display message catalog information and exit"
  [ "$output" = "$(echo -e "メッセージカタログ情報を表示して終了します")" ]
}
@test "Display this help and exit" {
  run $basecmd "Display this help and exit"
  [ "$output" = "$(echo -e "ヘルプを表示して終了します")" ]
}
@test "Display version information and exit" {
  run $basecmd "Display version information and exit"
  [ "$output" = "$(echo -e "バージョン情報を表示して終了します")" ]
}
@test "Specify the name of an existing PO file" {
  run $basecmd "Specify the name of an existing PO file"
  [ "$output" = "$(echo -e "存在する PO ファイルの名前を指定してください")" ]
}
@test "Specify the name of a new BATS file" {
  run $basecmd "Specify the name of a new BATS file"
  [ "$output" = "$(echo -e "新規 BATS ファイルの名前を指定してください")" ]
}
@test "See gettext command help for more information" {
  run $basecmd "See gettext command help for more information"
  [ "$output" = "$(echo -e "詳細は、gettext コマンドのヘルプをご覧ください")" ]
}
@test "Report bugs to" {
  run $basecmd "Report bugs to"
  [ "$output" = "$(echo -e "バグの報告先")" ]
}
@test "missing file operand" {
  run $basecmd "missing file operand"
  [ "$output" = "$(echo -e "ファイルオペランドがありません")" ]
}
@test "Try the following command" {
  run $basecmd "Try the following command"
  [ "$output" = "$(echo -e "次のコマンドをお試しください")" ]
}
@test "line" {
  run $basecmd "line"
  [ "$output" = "$(echo -e "行")" ]
}
@test "PO error" {
  run $basecmd "PO error"
  [ "$output" = "$(echo -e "PO エラー")" ]
}
@test "BATS error" {
  run $basecmd "BATS error"
  [ "$output" = "$(echo -e "BATS エラー")" ]
}
@test "TEXTDOMAIN error" {
  run $basecmd "TEXTDOMAIN error"
  [ "$output" = "$(echo -e "TEXTDOMAIN エラー")" ]
}
@test "TEXTDOMAINDIR error" {
  run $basecmd "TEXTDOMAINDIR error"
  [ "$output" = "$(echo -e "TEXTDOMAINDIR エラー")" ]
}
@test "This file was automatically generated by po2bats.sh. Do not edit!" {
  run $basecmd "This file was automatically generated by po2bats.sh. Do not edit!"
  [ "$output" = "$(echo -e "このファイルは po2bats.sh によって自動生成されました。編集しないでください！")" ]
}
@test "BATS tempfile error" {
  run $basecmd "BATS tempfile error"
  [ "$output" = "$(echo -e "BATS 一時ファイル・エラー")" ]
}
@test "Test counts" {
  run $basecmd "Test counts"
  [ "$output" = "$(echo -e "テスト回数")" ]
}
@test "Message not found" {
  run $basecmd "Message not found"
  [ "$output" = "$(echo -e "メッセージが見つかりません")" ]
}
@test "CHECKSUM (message digest) tempfile error" {
  run $basecmd "CHECKSUM (message digest) tempfile error"
  [ "$output" = "$(echo -e "チェックサム（メッセージ・ダイジェスト）一時ファイル・エラー")" ]
}
@test "CHECKSUM (message digest) for all translated messages" {
  run $basecmd "CHECKSUM (message digest) for all translated messages"
  [ "$output" = "$(echo -e "すべての翻訳済みメッセージに対するチェックサム（メッセージ・ダイジェスト）")" ]
}
@test "cannot move tempfile to target BATS file" {
  run $basecmd "cannot move tempfile to target BATS file"
  [ "$output" = "$(echo -e "一時ファイルを BATS ファイルへ移動できません")" ]
}
@test "Target BATS file not found" {
  run $basecmd "Target BATS file not found"
  [ "$output" = "$(echo -e "BATS ファイルが見つかりません")" ]
}
# テスト回数: 27
# すべての翻訳済みメッセージに対するチェックサム（メッセージ・ダイジェスト）: 1133daaf0bc6383b854bf2568197d950fea46c49cfeedafeaf8b50d295bfb97e
